image: ubuntu:bionic

build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  tags:
    - docker
    - ppc64le
  script:
    - "export DEBIAN_FRONTEND=noninteractive && apt -yqq update && apt install -yqq build-essential git tar bzip2 vim cmake python libcups2-dev pkg-config libnss3-dev libssl-dev libglib2.0-dev libgnome-keyring-dev libpango1.0-dev libdbus-1-dev libatk1.0-dev libatk-bridge2.0-dev libgtk-3-dev libkrb5-dev libpulse-dev libxss-dev re2c subversion curl libasound2-dev libpci-dev mesa-common-dev gperf bison nodejs uuid-dev clang-format libatspi2.0-dev"
    - "./ppc64le_build.bash"
    - "cd build/src/out/Default && tar ungoogled-chromium-linux-ppc64le-$CI_COMMIT_SHA.tar.bz2 -cvjSf --exclude=obj *"
  artifacts:
    paths:
      - "build/src/out/Default/ungoogled-chromium-linux-ppc64le-$CI_COMMIT_SHA.tar.bz2"
  cache:
    paths:
      - "build/src/out/Default/*"
      - "build/llvm_build/*"